TAG_DESCRIPTIONS = {
    "programme_anneedelamer25": "Ecologie",
    "local_anneedelamer25": "Ecologie",
    "numerique_anneedelamer25": "Ecologie",
    "livres_anneedelamer25": "Ecologie",
    "localart_ecologie25": "Ecologie",
    "numeriqueart_ecologie25": "Ecologie",
    "biensphysiques_bobdylan25": "Bob Dylan",
    "numerique_bobdylan25": "Bob Dylan",
    "local_tousalopera25": "Opera",
    "numerique_jea25": "Archeologie",
    "livres_jea25": "Archeologie",
    "local_jea25": "Archeologie",
    "localbresil_ameriquelatine25": "Bresil",
    "numeriquebresil_ameriquelatine25": "Bresil contenu numerique",
    "livresbresil_ameriquelatine25": "Bresil livres",
    "localmusique_ameriquelatine25": "Amerique Latine",
    "numeriquemusique_ameriquelatine25": "Amerique Latine numerique",
    "albumsmusique_ameriquelatine25": "Amerique Latine album musique au format numerique",
    "numeriquecuisine_ameriquelatine25": "Amerique Latine cuisine numerique",
    "livrescuisine_ameriquelatine25": "Amerique Latine livre cuisine",
    "livresrevolution_ameriquelatine25": "Amerique Latine livre revolution",
    "numeriquerevolution_ameriquelatine25": "Amerique Latine numerique revolution",
}
