
version: 1

models:
  - name: adage_involved_institution
    description: "Institutions whose have a cultural collaboration in Adage."
    columns:
      - name: date
        tests:
          - not_null
  - name: firebase_events
    description: "firebase events."

