MUSIQUE_LABEL = "Musique (CD, Vinyles, Instruments)"
LIVRE_LABEL = "Littérature (Livres, Bandes dessinés)"
CINEMA_LABEL = "Cinéma & Films (DVD)"
ART_LABEL = "Musées & Arts Visuels & Pratique Artistique (Cours, Ateliers)"
SORTIES_LABEL = "Sorties (Spectacle Vivant, Concerts & Festivals, Jeux, Conférences)"

CAT = {
    MUSIQUE_LABEL: [
        "CD",
        "Vinyles",
        "Instrument de musique",
        "Festivals",
        "Concert Live",
    ],
    SORTIES_LABEL: [
        "Pièce de théâtre",
        "Représentation en direct",
        "Conférence",
        "Danse",
        "Stand-up",
        "Opéra",
        "One-man show",
        "Escape Game",
    ],
    LIVRE_LABEL: [
        "Bandes dessinées",
        "Mangas",
        "Comics",
        "Jeunesse",
        "Vie pratique & Loisirs",
        "Sciences humaines & sociales",
        "Arts et spectacles",
        "Entreprise, économie & droit",
        "Sciences & Techniques",
        "Religion & Esotérisme",
        "Tourisme & Voyages",
        "Parascolaire",
        "Dictionnaires / Encyclopédies / Documentation",
        "Scolaire",
        "Essai",
        "Livre Audio",
        "Poésie",
        "Roman",
    ],
    CINEMA_LABEL: [
        "Animation",
        "Documentaire",
        "Biographie",
        "Places, Cartes & Abonnements",
        "Fiction",
        "Séries TV",
        "DVD / Blue Ray",
    ],
    ART_LABEL: [
        "Photographie",
        "Sculpture",
        "Peinture",
        "Art Comtemporain",
        "Arts graphiques",
        "Fournitures artistiques",
        "Jeux Videos",
    ],
}


GENRE = {
    MUSIQUE_LABEL: [
        "Blues",
        "Chanson française",
        "Dubstep",
        "Drum and bass",
        "Easy listening",
        "Electronic dance music",
        "Electronica",
        "Funk",
        "Gospel",
        "Heavy metal",
        "Jazz",
        "Classique",
        "Country",
        "Musique électronique",
        "Musique expérimentale",
        "Musique folk",
        "Musique instrumentale",
        "Musique latine",
        "Musique soul",
        "Musiques du monde",
        "New age",
        "Pop",
        "Rap",
        "Reggae",
        "RnB contemporain",
        "Rock",
        "K-Pop",
    ],
    SORTIES_LABEL: [
        "Cirque",
        "Conférence",
        "Danse Classique",
        "Danse Contemporaine",
        "Drame",
        "Ballet",
        "Orchestre",
        "Réalité virtuelle",
        "Escape Game",
        "Comédie Musicale",
        "Poésie",
        "Ballet",
        "Danse",
        "Escape Game",
        "Action/Aventure",
        "Comédie",
    ],
    LIVRE_LABEL: [
        "Histoire de l'art",
        "Jeux",
        "Droit",
        "Shônen (Manga)",
        "Shôjo (Manga)",
        "Sport",
        "Romance",
        "Humour",
        "Langue",
        "Santé",
        "Loisirs",
        "Economie",
        "Histoire",
        "Jeunesse",
        "Policier",
        "Tourisme",
        "Sexualité",
        "Sociologie",
        "Informatique",
        "Vie pratique",
        "Cuisine",
        "Bandes dessinées",
        "Carrière Concours",
        "Gestion entreprise",
        "Sciences, vie & Nature",
        "Littérature Etrangère",
        "Littérature française",
        "Scolaire & Parascolaire",
        "Littérature Européenne",
        "Géographie, cartographie",
        "Marketing et audio-visuel",
        "Psychanalyse, psychologie",
        "Religions, spiritualitées",
        "Poèsie, théâtre et spectacle",
        "Science-fiction, Fantastique & Terreur",
        "Sciences Humaines, Encyclopédie, Dictionnaire",
    ],
    CINEMA_LABEL: [
        "Action",
        "Animation",
        "Arts Martiaux",
        "Aventure",
        "Biopic",
        "Documentaire",
        "Drame",
        "Comédie",
        "Comédie dramatique",
        "Comédie musicale",
        "Epouvante-horreur",
        "Erotisme",
        "Espionnage",
        "Familial",
        "Fantastique",
        "Feuilleton",
        "Guerre",
        "Historique",
        "Judiciaire",
        "Musical",
        "Médical",
        "Policier",
        "Péplum",
        "Romance",
        "Science Fiction",
        "Thriller",
        "Western",
    ],
    ART_LABEL: [
        "Dessin",
        "Peinture",
        "Photographie",
        "Sculture",
        "Arts Plastiques",
        "Art Comtemporain",
        "Arts graphiques",
        "Histoire de l'art",
        "Réalité virtuelle",
        "Cours de Couture",
        "Cours de Peinture",
        "Cours de Dessin",
    ],
}


MEDIUM = {
    MUSIQUE_LABEL: [
        "CD",
        "Vinyle",
        "Studio d'Enregistrement",
        "Album",
        "Pratique Artistique",
        "Guitare",
        "Saxophone",
        "Piano",
        "Scène",
        "Concert",
    ],
    SORTIES_LABEL: [
        "Physique",
        "Numérique",
        "Studio d'Enregistrement",
        "Rencontre en ligne",
        "Réalité virtuelle",
        "Escape Game",
        "Jeu de Société",
        "Scène",
        "Concert Live",
        "Pièce Théatre",
    ],
    LIVRE_LABEL: [
        "Papier",
        "Numérique",
        "Audio",
        "Bande dessinée",
        "Manga",
    ],
    CINEMA_LABEL: [
        "Vidéos",
        "Numérique",
        "Streaming",
        "Physique",
        "Billet/Ticket",
        "Carte & Abonnement",
    ],
    ART_LABEL: [
        "Dessin",
        "Peinture",
        "Acquarelle",
        "Photographie",
        "Grandeur Nature",
        "Feutres",
        "Papier",
        "Crayons de Couleur",
        "Réalité virtuelle",
        "Jeu de Société",
        "Grandeur Nature",
    ],
}
