version: 2

updates:
  #############################################################
  ###################        Root Dir       ###################
  #############################################################
  - package-ecosystem: "uv"
    open-pull-requests-limit: 0
    directory: "."
    schedule:
      interval: "daily"
    commit-message:
      prefix: "(BSR) chore(dependabot): "
    groups:
      root-project:
        applies-to: security-updates
        patterns:
          - "*"

  #############################################################
  ###################        ETL JOBS       ###################
  #############################################################
  - package-ecosystem: "uv"
    open-pull-requests-limit: 0
    directory: "jobs/etl_jobs/internal/sync_recommendation"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "(BSR) chore(dependabot): "
    groups:
      sync-recommendation:
        applies-to: security-updates
        patterns:
          - "*"

  #############################################################
  ###################        ML JOBS        ###################
  #############################################################
  # Separate groups for each ML job
  - package-ecosystem: "uv"
    open-pull-requests-limit: 0
    directory: "jobs/ml_jobs/algo_training"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "(BSR) chore(dependabot): "
    groups:
      ml-algo-training:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: "uv"
    open-pull-requests-limit: 0
    directory: "jobs/ml_jobs/artist_linkage"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "(BSR) chore(dependabot): "
    groups:
      ml-artist-linkage:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: "uv"
    open-pull-requests-limit: 0
    directory: "jobs/ml_jobs/clusterisation"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "(BSR) chore(dependabot): "
    groups:
      ml-clusterisation:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: "uv"
    open-pull-requests-limit: 0
    directory: "jobs/ml_jobs/edito_semantic_search"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "(BSR) chore(dependabot): "
    groups:
      ml-edito-semantic-search:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: "uv"
    open-pull-requests-limit: 0
    directory: "jobs/ml_jobs/embeddings"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "(BSR) chore(dependabot): "
    groups:
      ml-embeddings:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: "uv"
    open-pull-requests-limit: 0
    directory: "jobs/ml_jobs/endpoint_monitoring"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "(BSR) chore(dependabot): "
    groups:
      ml-endpoint-monitoring:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: "uv"
    open-pull-requests-limit: 0
    directory: "jobs/ml_jobs/finance"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "(BSR) chore(dependabot): "
    groups:
      ml-finance:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: "uv"
    open-pull-requests-limit: 0
    directory: "jobs/ml_jobs/graph_recommendation"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "(BSR) chore(dependabot): "
    groups:
      ml-graph-recommendation:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: "uv"
    open-pull-requests-limit: 0
    directory: "jobs/ml_jobs/item_embeddings"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "(BSR) chore(dependabot): "
    groups:
      ml-item-embeddings:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: "uv"
    open-pull-requests-limit: 0
    directory: "jobs/ml_jobs/item_linkage"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "(BSR) chore(dependabot): "
    groups:
      ml-item-linkage:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: "uv"
    open-pull-requests-limit: 0
    directory: "jobs/ml_jobs/offer_compliance"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "(BSR) chore(dependabot): "
    groups:
      ml-offer-compliance:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: "uv"
    open-pull-requests-limit: 0
    directory: "jobs/ml_jobs/ranking_endpoint"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "(BSR) chore(dependabot): "
    groups:
      ml-ranking-endpoint:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: "uv"
    open-pull-requests-limit: 0
    directory: "jobs/ml_jobs/reduction"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "(BSR) chore(dependabot): "
    groups:
      ml-reduction:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: "uv"
    open-pull-requests-limit: 0
    directory: "jobs/ml_jobs/retrieval_vector"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "(BSR) chore(dependabot): "
    groups:
      ml-retrieval-vector:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: "uv"
    open-pull-requests-limit: 0
    directory: "jobs/ml_jobs/semantic_search_lancedb"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "(BSR) chore(dependabot): "
    groups:
      ml-semantic-search-lancedb:
        applies-to: security-updates
        patterns:
          - "*"
