version: 2

updates:
  - package-ecosystem: "uv"
    directory: "/jobs/ml_jobs/retrieval_vector"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
    groups:
      retrieval-vector-security:
        patterns:
          - "*"
