version: 2

updates:
  - package-ecosystem: "uv"
    directory: "/jobs/ml_jobs/retrieval_vector"
    schedule:
      interval: "daily"
    groups:
      retrieval-vector-security:
        patterns:
          - "*"
  - package-ecosystem: "uv"
    directory: "."
    schedule:
      interval: "daily"
    groups:
      project-security:
        patterns:
          - "/pyproject.toml"
          - "/uv.lock"
