[tool.poetry]
name = "data-gcp"
version = "0.1.0"
description = "GCP services applicative implementation"
authors = [
    "Team Data"
]
readme = 'README.md'  # Markdown files are supported

repository = "https://github.com/pass-culture/data-gcp"

keywords = ['packaging', 'poetry']

[tool.poetry.dependencies]
python = "^3.7"
google-cloud-bigquery = "^2.2.0"
Flask = "^1.1.2"
gunicorn = "^20.0.4"

[tool.poetry.dev-dependencies]
pytest = "^6.1.1"
pytest-cov = "^2.10.1"
apache-airflow = "^1.10.10"
