version: 2

models:
  - name: int_applicative__user
    description: ""
    columns:
      - name: user_department_code
        description: |
          set 99 when user user_creation_date does not match opening phases.
          this is due to Support changes in the past which migh lead to misunderstandings.
          if user_department is not in pilote (2019_02 / 2019_06) phase but has created an account before, set 99.
          if user_department is not in experimentation (2019_06 / 2021_05) phase but has created an account before, set 99.
        tests:
          - not_null