version: 1

models:
  - name: siren_data
    config: 
      materialized: view
      tags: ["pro"]
    columns:
      - name: siren
        tests: 
          - not_null
          - unique
      - name: categorieEntreprise
        tests:
          - relationships:
              to: ref('region_department')
              field: dep_name
              severity: 'error'
          - accepted_values:
              values: ['PME','GE']
              error_if: '>=10'
  - name: enriched_cultural_partner_data
    config: 
      materialized: table
      tags: ["pro"]
    columns:
      - name: venue_id
        tests: 
          - unique
  - name: applicative_database_offer
    tests:
      - elementary.freshness_anomalies:
          severity: error
          timestamp_column: "CAST(offer_creation_date AS TIMESTAMP)" # Mandatory
          where_expression: "NOT offer_is_duo"
          time_bucket: # Daily by default
            period: day
            count: 1


