[project]
name = "titelive"
version = "0.1.0"
description = "Titelive ETL pipeline with multiple execution modes"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.9.0",
    "backoff>=2.2.1",
    "gcloud-aio-storage>=9.6.0",
    "google-cloud-bigquery>=3.0.0",
    "google-cloud-secret-manager>=2.24.0",
    "google-cloud-storage>=2.16.0",
    "httpx>=0.27.0",
    "pandas>=2.2.0",
    "pandas-gbq>=0.19.0",
    "pyarrow>=21.0.0",
    "pytest>=8.2.2",
    "requests>=2.31.0",
    "tqdm>=4.67.0",
    "typer>=0.12.3",
]

[tool.ruff]
target-version = 'py312'

lint.select = [
    "E",      # pycodestyle
    "W",      # pycodestyle
    "F",      # Pyflakes
    "B",      # flake8-bugbear
    "C4",     # flake8-comprehensions
    "I",      # isort
    "SIM",    # flake8-simplify
    "UP",     # pyupgrade
    "RUF",    # Ruff-specific rules
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"
