version: 2.1

workflows:
  version: 2
  run-tests:
    jobs:
      - build
      - api-tests:
          requires:
            - build


jobs:
  build:
    docker:
      - image: circleci/python:3.7
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/data-gcp
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "api/requirements.txt" }}
      - run:
          name: Install Python deps in a venv
          command: |
            cd api
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: dependencies-{{ checksum "api/requirements.txt" }}
          paths:
            - "venv"

  api-tests:
    docker:
      - image: circleci/python:3.7
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/data-gcp/api
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Activate venv
          command: |
            . venv/bin/activate
      - run:
          name: Run tests
          command: |
            pytest --cov
