version: 2.1

workflows:
  version: 2
  run-checks:
    jobs:
      - install
      - linter:
          requires:
            - install
      - recommendation-db-tests:
          requires:
            - install
      - recommendation-api-build
      - recommendation-api-tests:
          requires:
            - recommendation-api-build
      - orchestration-install
      - orchestration-tests:
          requires:
            - orchestration-install
      - composer-deploy:
          requires:
            - orchestration-tests
          filters:
            branches:
              only:
                - master

defaults: &defaults
  docker:
    - image: circleci/python:3.7
      auth:
        username: $DOCKERHUB_USER
        password: $DOCKERHUB_PASSWORD

jobs:
  recommendation-api-build:
    <<: *defaults
    working_directory: ~/data-gcp/recommendation/api
    steps:
      - checkout:
          path: ~/data-gcp
      - restore_cache:
          key: dependencies-{{ checksum "dev-requirements.txt" }}
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv-api
            . venv-api/bin/activate
            pip install -r dev-requirements.txt
      - save_cache:
          key: dependencies-{{ checksum "dev-requirements.txt" }}
          paths:
            - "venv-api"
      - persist_to_workspace:
          root: .
          paths:
            - .

  recommendation-api-tests:
    docker:
      - image: circleci/python:3.7
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
      - image: circleci/postgres:12
        environment:
          POSTGRES_PASSWORD: postgres
    working_directory: ~/data-gcp/recommendation/api
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install psql
          command: sudo apt install postgresql-client
      - run:
          name: Run tests
          command: |
            export PYTHONPATH=$PYTHONPATH:~/data-gcp/recommendation/api
            . venv-api/bin/activate
            ./run_tests.sh

  install:
    <<: *defaults
    working_directory: ~/data-gcp
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - data-gcp-{{ checksum "poetry.lock" }}
      - run:
          name: Install dependencies
          command: |
            poetry run pip install --upgrade pip
            poetry install
      - save_cache:
          key: data-gcp-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs

  linter:
    <<: *defaults
    working_directory: ~/data-gcp
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - data-gcp-{{ checksum "poetry.lock" }}
      - run:
          name: Run linter
          command: poetry run black --check .



  orchestration-install:
    <<: *defaults
    working_directory: ~/data-gcp/orchestration
    steps:
      - checkout:
          path: ~/data-gcp
      - restore_cache:
          key: orchestration-{{ checksum "orchestration-requirements.txt" }}
      - run:
          name: Install Python requirements
          command: |
            python3 -m venv venv-orchestration
            . venv-orchestration/bin/activate
            pip install -r orchestration-requirements.txt
      - save_cache:
          key: orchestration-{{ checksum "orchestration-requirements.txt" }}
          paths:
            - "venv-orchestration"
      - persist_to_workspace:
          root: .
          paths:
            - .

  orchestration-tests:
    <<: *defaults
    working_directory: ~/data-gcp/orchestration
    environment:
      - AIRFLOW_HOME=~/data-gcp/orchestration
      - RECOMMENDATION_SQL_USER=test_user
      - RECOMMENDATION_SQL_PASSWORD=test_password
      - RECOMMENDATION_SQL_PUBLIC_PORT=1234
      - RECOMMENDATION_SQL_PUBLIC_IP=11.111.111.111
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          command: |
            . venv-orchestration/bin/activate
            airflow initdb
            pytest tests

  recommendation-db-tests:
    docker:
      - image: circleci/python:3.7
      - image: circleci/postgres:12
        environment:
          POSTGRES_PASSWORD: postgres
    working_directory: ~/data-gcp
    steps:
      - checkout
      - restore_cache:
          key: data-gcp-{{ checksum "poetry.lock" }}
      - run:
          name: Install psql
          command: sudo apt install postgresql-client
      - run:
          name: Run tests
          command: ./run_tests.sh

  composer-deploy:
    docker:
      - image: google/cloud-sdk
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    environment:
      COMPOSER_BUCKET: gs://europe-west1-data-composer-0f2400f5-bucket/dags
      COMPOSER_ENV_NAME: data-composer
      COMPOSER_REGION: europe-west1
      DAG_RESTORE_DATA_ANALYTICS: restore_data_analytics_v1
      DAG_RECOMMMENDATION_CLOUDSQL: recommendation_cloud_sql_v6
    working_directory: ~/data-gcp/dags
    steps:
      - checkout:
          path: ~/data-gcp
      - run:
          name: Connect to GCP
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      - run:
          name: Deploy to composer
          command: |
            gsutil -m rsync -c -r . ${COMPOSER_BUCKET}
      - run:
          name: Wait for dags to be deployed
          command: |
            ./wait_for_dag_deployed.sh ${COMPOSER_ENV_NAME} ${COMPOSER_REGION} ${DAG_RECOMMMENDATION_CLOUDSQL} 6 20
            ./wait_for_dag_deployed.sh ${COMPOSER_ENV_NAME} ${COMPOSER_REGION} ${DAG_RESTORE_DATA_ANALYTICS} 6 20
