[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flask==3.0.0",
    "flask-cors==6.0.0",
    "hypercorn==0.15.0",
    "lightgbm==4.6.0",
    "numpy==1.26.4",
    "pandas==2.0.3",
    "pyarrow==16.1.0",
    "python-json-logger==2.0.7",
    "scikit-learn==1.5.1",
    "h11==0.16.0",
]
[tool.uv]
environments = [
    "sys_platform == 'darwin'",
    "sys_platform == 'linux'",
]
