# Configuration for item embedding vectors
# Each vector defines which features to include in the embedding prompt and the model to use for embedding extraction

# Features will be concatenated in the order specified for each vector type
# Feature may have an optional label override in the "labels" section, which will be used in the prompt instead of the column name
# e.g. the "semantic_content" vector will encode:
    # titre de l'offre : <offer_name_value>
    # catégorie : <category_id_value>
# into a single prompt for embedding extraction

## Available prompt_names for embeddinggemma:
# ['query', 'document', 'BitextMining', 'Clustering', 'Classification',
# 'InstructionRetrieval', 'MultilabelClassification', 'PairClassification',
# 'Reranking', 'Retrieval', 'Retrieval-query', 'Retrieval-document', 'STS', 'Summarization'].
# (see https://huggingface.co/google/embeddinggemma-300m)

vectors:
  - name: "semantic_content"
    features:
      - offer_name
      - category_id
      - subcategory_id
      - offer_label_concat
      - author_concat
      - offer_description
    encoder_name: "google/embeddinggemma-300m"
    prompt_name: "document"  # "document" prompt: "title: none | text: {content}"
    labels:
      offer_name: "titre de l'offre"
      category_id: "catégorie"
      subcategory_id: "sous-catégorie"
      offer_label_concat: "genres"
      author_concat: "auteur/artiste"
      offer_description: "description"


  # - name: "image_content"
  #   features:
  #     - image
  #   encoder_name: "clip-ViT-B-32"
