PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>

SELECT
  ?wikidata_id
  ?spotify_id
  ?isni_id
  ?apple_music_id
  ?deezer_id
  ?genius_id
  ?soundcloud_id
  (
    IF(BOUND(?genius_id), 1, 0) +
    IF(BOUND(?spotify_id), 1, 0) +
    IF(BOUND(?deezer_id), 1, 0) +
    IF(BOUND(?isni_id), 1, 0) +
    IF(BOUND(?apple_music_id), 1, 0) +
    IF(BOUND(?soundcloud_id), 1, 0)
  AS ?matching_score)
WHERE {
  {
    SELECT
      ?wikidata_id
      (MIN(?genius_id_raw) AS ?genius_id)
      (MIN(?spotify_id_raw) AS ?spotify_id)
      (MIN(?deezer_id_raw) AS ?deezer_id)
      (MIN(?isni_id_raw) AS ?isni_id)
      (MIN(?apple_music_id_raw) AS ?apple_music_id)
      (MIN(?soundcloud_id_raw) AS ?soundcloud_id)
    WHERE {
      {
        { ?wikidata_id wdt:P2373 [] . }
        UNION { ?wikidata_id wdt:P1902 [] . }
        UNION { ?wikidata_id wdt:P2722 [] . }
        UNION { ?wikidata_id wdt:P2850 [] . }
        UNION { ?wikidata_id wdt:P3040 [] . }
      }

      ?wikidata_id wdt:P31 ?type .
      VALUES ?type { wd:Q5 wd:Q215380 wd:Q216337 wd:Q641066 }

      OPTIONAL { ?wikidata_id wdt:P2373 ?genius_id_raw . }
      OPTIONAL { ?wikidata_id wdt:P1902 ?spotify_id_raw . }
      OPTIONAL { ?wikidata_id wdt:P2722 ?deezer_id_raw . }
      OPTIONAL { ?wikidata_id wdt:P213 ?isni_id_raw . }
      OPTIONAL { ?wikidata_id wdt:P2850 ?apple_music_id_raw . }
      OPTIONAL { ?wikidata_id wdt:P3040 ?soundcloud_id_raw . }
    }
    GROUP BY ?wikidata_id
  }
}