with
    bookable_offer_history as (
        select
            venue_id,
            min(partition_date) as first_bookable_offer_date,
            max(partition_date) as last_bookable_offer_date,
            min(
                case when individual_bookable_offers > 0 then partition_date end
            ) as first_individual_bookable_offer_date,
            max(
                case when individual_bookable_offers > 0 then partition_date end
            ) as last_individual_bookable_offer_date,
            min(
                case when collective_bookable_offers > 0 then partition_date end
            ) as first_collective_bookable_offer_date,
            max(
                case when collective_bookable_offers > 0 then partition_date end
            ) as last_collective_bookable_offer_date
        from {{ ref("bookable_venue_history") }}
        group by venue_id
    )

select
    v.venue_id,
    v.venue_name,
    v.venue_public_name,
    v.venue_booking_email,
    v.venue_street,
    v.venue_latitude,
    v.venue_longitude,
    v.venue_department_code,
    v.venue_department_name,
    v.venue_postal_code,
    v.venue_city,
    v.venue_siret,
    v.venue_is_virtual,
    v.venue_managing_offerer_id,
    v.venue_creation_date,
    v.venue_is_permanent,
    v.venue_is_open_to_public,
    v.venue_is_acessibility_synched,
    v.venue_type_label,
    v.venue_label,
    v.venue_humanized_id,
    v.venue_backoffice_link,
    v.venue_region_name,
    v.venue_epci,
    v.venue_density_label,
    v.venue_macro_density_label,
    v.venue_density_level,
    v.venue_academy_name,
    v.venue_in_qpv,
    v.venue_targeted_audience,
    v.banner_url,
    v.venue_description,
    v.venue_withdrawal_details,
    v.venue_contact_phone_number,
    v.venue_contact_email,
    v.venue_contact_website,
    v.total_individual_bookings,
    v.total_collective_bookings,
    v.total_bookings,
    v.total_non_cancelled_individual_bookings,
    v.total_non_cancelled_collective_bookings,
    v.first_individual_booking_date,
    v.last_individual_booking_date,
    v.first_collective_booking_date,
    v.last_collective_booking_date,
    v.total_non_cancelled_bookings,
    v.total_used_bookings,
    v.total_used_individual_bookings,
    v.total_used_collective_bookings,
    v.total_individual_theoretic_revenue,
    v.total_individual_real_revenue,
    v.total_collective_theoretic_revenue,
    v.total_collective_real_revenue,
    v.total_theoretic_revenue,
    v.total_real_revenue,
    v.first_individual_offer_creation_date,
    v.last_individual_offer_creation_date,
    v.total_created_individual_offers,
    v.first_collective_offer_creation_date,
    v.last_collective_offer_creation_date,
    v.total_created_collective_offers,
    v.total_created_offers,
    v.first_bookable_offer_date,
    v.last_bookable_offer_date,
    v.first_individual_bookable_offer_date,
    v.last_individual_bookable_offer_date,
    v.first_collective_bookable_offer_date,
    v.last_collective_bookable_offer_date,
    v.first_booking_date,
    v.last_booking_date,
    v.first_offer_creation_date,
    v.last_offer_creation_date,
    v.total_bookable_individual_offers,
    v.total_bookable_collective_offers,
    v.total_bookable_offers,
    v.total_non_cancelled_tickets,
    v.total_current_year_non_cancelled_tickets,
    v.offerer_id,
    v.offerer_name,
    v.offerer_validation_status,
    v.offerer_is_active,
    v.dms_accepted_at,
    v.first_dms_adage_status,
    v.is_reference_adage,
    v.is_synchro_adage,
    v.venue_pc_pro_link,
    v.partner_id,
    v.venue_iris_internal_id,
    v.offerer_address_id,
    v.offerer_rank_desc,
    v.offerer_rank_asc,
    v.venue_image_source,
    v.venue_adage_inscription_date,
    coalesce(date_diff(current_date, boh.last_bookable_offer_date, day) <= 30, false) as is_active_last_30days,
    coalesce(date_diff(current_date, boh.last_bookable_offer_date, year) = 0, false) as is_active_current_year,
    coalesce(date_diff(current_date, boh.last_individual_bookable_offer_date, day) <= 30, false) as is_individual_active_last_30days,
    coalesce(date_diff(current_date, boh.last_individual_bookable_offer_date, year) = 0, false) as is_individual_active_current_year,
    coalesce(date_diff(current_date, boh.last_collective_bookable_offer_date, day) <= 30, false) as is_collective_active_last_30days,
    coalesce(date_diff(current_date, boh.last_collective_bookable_offer_date, year) = 0, false) as is_collective_active_current_year
from {{ ref("int_global__venue") }} as v
left join bookable_offer_history as boh on v.venue_id = boh.venue_id
where v.offerer_validation_status = 'VALIDATED' and v.offerer_is_active
