version: 2

models:

  - name: mrt_global__venue
    description: "This table that consolidates comprehensive details about venues at the `venue_id` granularity."

  - name: mrt_global__offer
    description: "This table contains all offers that are approved."
  
