[project]
name = "metabase"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "google-auth-oauthlib==1.2.0",
    "google-cloud-secret-manager==2.20.0",
    "pandas==2.2.2",
    "pandas-gbq==0.23.1",
    "pytest>=8.4.2",
    "requests==2.32.3",
    "tqdm==4.58.0",
    "typer==0.12.3",
]
