name: 'data_gcp_dbt'
version: '1.0.0'
config-version: 2

flags:
  send_anonymous_usage_stats: False
  require_explicit_package_overrides_for_builtin_materializations: false

profile: 'data_gcp_dbt'

model-paths: [ "models" ]
analysis-paths: [ "analyses" ]
test-paths: [ "tests" ]
seed-paths: [ "seeds" ]
macro-paths: [ "macros" ]
snapshot-paths: [ "snapshots" ]

packages-install-path: "{{ env_var('DBT_TARGET_PATH', 'target') }}/dbt_packages"

clean-targets:
  - "{{ env_var('DBT_TARGET_PATH', 'target') }}"

models:
  data_gcp_dbt:
    +pre-hook:
      - "{{ create_schema_dev() }}"
    +post-hook:
      - "{{ set_table_expiration_dev() }}"
    +labels:
      schedule: "daily"
    +persist_docs:
      relation: true
      columns: true
    raw:  # Hide "raw" folder
      +meta:
        owner: "@team-data-engineering"
      +materialized: "{{ var('CI_MATERIALIZATION', 'table') }}"
      +schema: raw_applicative_{{ target.name }}
      +docs:
        show: false
    clean:  # Hide "clean" folder
      +meta:
        owner: "@team-data-engineering"
      +materialized: "{{ var('CI_MATERIALIZATION', 'table') }}"
      +schema: clean_{{ target.name }}
      +docs:
        show: false
    analytics:  # Hide "analytics" folder
      +meta:
        owner: "@team-data-analytics"
      +materialized: "{{ var('CI_MATERIALIZATION', 'table') }}"
      +schema: analytics_{{ target.name }}
      +docs:
        show: false
    intermediate:
      +meta:
        owner: "@team-data-engineering"
      +materialized: "{{ var('CI_MATERIALIZATION', 'view') }}"
    mart:
      +meta:
        owner: "@team-data-analytics"
      +materialized: "{{ var('CI_MATERIALIZATION', 'table') }}"
      +schema: analytics_{{ target.name }}
    export:  # Hide "export" folder
      +schema: export_{{ target.name }}
      +materialized: "{{ var('CI_MATERIALIZATION', 'view') }}"
      +meta:
        owner: "@team-data-engineering"
      +docs:
        show: false
    machine_learning:  # Hide "machine_learning" folder
      +materialized: "{{ var('CI_MATERIALIZATION', 'table') }}"
      +meta:
        owner: "@team-data-science"
      +docs:
        show: false

  dbt_utils:
    +docs:
      show: false

  elementary:
    +docs:
      show: false

seeds:
  +schema: seeds
  +docs:
    node_color: "#000000"
    show: false

snapshots:
  +target_schema: snapshot_{{ target.name }}
  +docs:
    show: false

data_tests:
  +store_failures: true
  +severity: "{{ env_var('CI_SEVERITY', 'warn') }}"
  +docs:
    show: false
    tags: "test"

vars:
  ENV_SHORT_NAME: dev
  CI_MATERIALIZATION: none
  region_name: region-europe-west1
  mute_ensure_materialization_override: true
  snapshot_filter: "dbt_valid_to is null"
