config:
  send_anonymous_usage_stats: False

data_gcp_dbt:
  target: dev
  outputs:
    dev:
      dataset: tmp_dev
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: europe-west1
      method: oauth
      priority: interactive
      project: passculture-data-ehp
      threads: 1
      type: bigquery
    stg:
      dataset: tmp_stg
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: europe-west1
      method: oauth
      priority: interactive
      project: passculture-data-ehp
      threads: 1
      type: bigquery
    prod:
      dataset: tmp_prod
      job_execution_timeout_seconds: 1200
      job_retries: 4
      location: europe-west1
      method: oauth
      priority: interactive
      project: passculture-data-prod
      threads: 1
      type: bigquery
sandbox:
  target: prod
  outputs:
    prod:
      dataset: dbt_sandbox_prod
      job_execution_timeout_seconds: 3600
      job_retries: 4
      location: europe-west1
      method: oauth
      priority: interactive
      project: passculture-data-prod
      threads: 1
      type: bigquery

elementary:
  target: dev
  outputs:
    dev:
      dataset: dbt_artifacts_dev
      type: bigquery
      method: oauth
      project: passculture-data-ehp
      location: europe-west1
      threads: 2
    stg:
      dataset: dbt_artifacts_stg
      type: bigquery
      method: oauth
      project: passculture-data-ehp
      location: europe-west1
      threads: 2
    prod:
      dataset: dbt_artifacts_prod
      type: bigquery
      method: oauth
      project: passculture-data-prod
      location: europe-west1
      threads: 2

CI:
  target: dev
  outputs:
    dev:
      dataset: ci_dev
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: europe-west1
      method: oauth
      priority: interactive
      project: passculture-data-ehp
      threads: 1
      type: bigquery
    stg:
      dataset: ci_stg
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: europe-west1
      method: oauth
      priority: interactive
      project: passculture-data-ehp
      threads: 1
      type: bigquery
    prod:
      dataset: ci_prod
      job_execution_timeout_seconds: 1200
      job_retries: 4
      location: europe-west1
      method: oauth
      priority: interactive
      project: passculture-data-prod
      threads: 1
      type: bigquery