data_gcp_dbt:
  outputs:
    dev:
      dataset: tmp_dev
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: europe-west1
      method: oauth
      priority: interactive
      project: passculture-data-ehp
      threads: 1
      type: bigquery
  target: dev
