version: "3.7"

services:
  testdb:
    image: postgis/postgis:12-3.3
    container_name: testdb
    ports:      
      - "${DATA_GCP_TEST_POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_PASSWORD=postgres