version: 2

macros:

  - name: exp_posthog_pro_event
    description: "Materialized view export for a Product Analytics Tool using a simplified schema of firebase partner events."

  - name: exp_posthog__native_event
    description: "Materialized view export for a Product Analytics Tool using a simplified schema of firebase native events."
  
  - name: exp_posthog__adage_log
    description: "Materialized view export for a Product Analytics Tool using a simplified schema of adage events."
