CREATE TABLE public.offer_context (
    id SERIAL PRIMARY KEY,
    call_id varchar,
    context varchar,
    date timestamp,
    user_id varchar,
    user_bookings_count float,
    user_clicks_count float,
    user_favorites_count float,
    user_deposit_remaining_credit varchar,
    user_iris_id varchar,
    user_latitude varchar,
    user_longitude varchar,
    offer_user_distance float,
    offer_id varchar,
    offer_item_id varchar,
    offer_booking_number int,
    offer_stock_price float,
    offer_creation_date timestamp,
    offer_stock_beginning_date timestamp,
    offer_category varchar,
    offer_subcategory_id varchar,
    offer_item_score float,
    offer_order varchar,
    offer_venue_id varchar
)