
dbt_clickhouse:
  target: local
  outputs:
    local:
      type: clickhouse
      driver: http
      host: localhost
      port: 8123
      schema: default
      user: "{{ env_var('CLICKHOUSE_USER') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD_DEV') }}"
      secure: False
      timeout: 300
    dev: # a consolider avec les ops
      type: clickhouse
      driver: http
      host: "{{ env_var('LOADBALANCER_IP') }}" # loadbalencer external IP
      port: 8123
      schema: default
      user: "{{ env_var('CLICKHOUSE_USER') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD_DEV') }}"
      secure: False
      timeout: 300
