from datetime import datetime

# enriched_offer_data
ENRICHED_OFFER_DATA_INPUT = {
    "booking": [
        {
            "user_id": "1",
            "stock_id": "1",
            "booking_id": "4",
            "booking_quantity": "2",
            "booking_creation_date": "2019-11-20",
            "booking_token": "ABC123",
            "booking_amount": "0",
            "booking_is_cancelled": False,
            "booking_is_used": False,
            "booking_used_date": "2019-11-22",
        },
    ],
    "favorite": [
        {"id": "1", "offerId": "3", "userId": "1"},
        {"id": "2", "offerId": "4", "userId": "2"},
        {"id": "3", "offerId": "3", "userId": "3"},
    ],
    "offer": [
        {
            "venue_id": "1",
            "product_id": "1",
            "offer_id": "3",
            "offer_type": "EventType.CINEMA",
            "offer_name": "Test",
            "offer_is_active": True,
            "offer_media_urls": '["https://url.test", "https://someurl.test"]',
            "offer_url": None,
            "offer_is_national": False,
            "offer_creation_date": "2019-11-20",
            "offer_is_duo": False,
            "offer_fields_updated": "{}",
        },
        {
            "venue_id": "2",
            "product_id": "2",
            "offer_id": "4",
            "offer_type": "ThingType.LIVRE_EDITION",
            "offer_name": "RIP Dylan Rieder",
            "offer_is_active": True,
            "offer_media_urls": '["https://url.test", "https://someurl.test"]',
            "offer_url": None,
            "offer_is_national": False,
            "offer_creation_date": "2019-11-20",
            "offer_is_duo": False,
            "offer_fields_updated": "{}",
        },
    ],
    "offerer": [
        {
            "offerer_id": "3",
            "offerer_thumb_count": "0",
            "offerer_is_active": True,
            "offerer_postal_code": "93100",
            "offerer_city": "Montreuil",
            "offerer_creation_date": "2019-11-20",
            "offerer_name": "Test Offerer",
            "offerer_siren": "123456789",
            "offerer_fields_updated": "{}",
        },
        {
            "offerer_id": "4",
            "offerer_siren": "234567890",
            "offerer_thumb_count": "0",
            "offerer_is_active": True,
            "offerer_postal_code": "93100",
            "offerer_city": "Montreuil",
            "offerer_creation_date": "2019-11-20",
            "offerer_name": "Test Offerer",
            "offerer_fields_updated": "{}",
        },
    ],
    "payment": [
        {
            "bookingId": "4",
            "id": "1",
            "amount": "10",
            "reimbursementRule": "test",
            "reimbursementRate": "1",
            "recipientName": "Toto",
            "recipientSiren": "123456789",
            "author": "test",
        },
    ],
    "payment_status": [
        {"paymentId": "1", "id": "1", "date": "2019-01-01", "status": "PENDING"},
    ],
    "product": [
        {
            "id": "1",
            "type": "EventType.CINEMA",
            "thumbCount": "0",
            "name": "Livre",
            "mediaUrls": '["https://url.test", "https://someurl.test"]',
            "fieldsUpdated": "{}",
            "url": None,
            "isNational": False,
        },
        {
            "id": "2",
            "type": "ThingType.LIVRE_EDITION",
            "thumbCount": "0",
            "name": "Livre",
            "mediaUrls": '["https://url.test", "https://someurl.test"]',
            "fieldsUpdated": "{}",
            "url": None,
            "isNational": False,
        },
    ],
    "stock": [
        {
            "stock_id": "1",
            "offer_id": "3",
            "stock_creation_date": "2019-11-01",
            "stock_quantity": "10",
            "stock_booking_limit_date": "2019-11-23",
            "stock_beginning_date": "2019-11-24",
            "stock_is_soft_deleted": False,
            "stock_modified_date": "2019-11-20",
            "stock_price": "0",
            "stock_fields_updated": "{}",
        },
        {
            "stock_id": "2",
            "offer_id": "4",
            "stock_creation_date": "2019-10-01",
            "stock_quantity": "12",
            "stock_is_soft_deleted": False,
            "stock_modified_date": "2019-11-20",
            "stock_price": "0",
            "stock_booking_limit_date": None,
            "stock_beginning_date": None,
            "stock_fields_updated": "{}",
        },
    ],
    "user": [
        {
            "user_id": "1",
            "user_email": "test@email.com",
            "user_can_book_free_offers": True,
            "user_is_admin": False,
            "user_postal_code": "93100",
            "user_department_code": "93",
            "user_public_name": "Test",
            "user_creation_date": "2018-11-20",
            "user_needs_to_fill_cultural_survey": True,
            "user_cultural_survey_filled_date": None,
        },
        {
            "user_id": "2",
            "user_email": "other@test.com",
            "user_can_book_free_offers": True,
            "user_is_admin": False,
            "user_postal_code": "93100",
            "user_department_code": "93",
            "user_public_name": "Test",
            "user_creation_date": "2018-11-20",
            "user_needs_to_fill_cultural_survey": True,
            "user_cultural_survey_filled_date": None,
        },
        {
            "user_id": "3",
            "user_email": "louie.lopez@test.com",
            "user_can_book_free_offers": True,
            "user_is_admin": False,
            "user_postal_code": "93100",
            "user_department_code": "93",
            "user_public_name": "Test",
            "user_creation_date": "2018-11-20",
            "user_needs_to_fill_cultural_survey": True,
            "user_cultural_survey_filled_date": None,
        },
    ],
    "venue": [
        {
            "venue_managing_offerer_id": "3",
            "venue_id": "1",
            "venue_siret": "12345678900026",
            "venue_thumb_count": "0",
            "venue_name": "Test Venue",
            "venue_postal_code": "93",
            "venue_city": "Montreuil",
            "venue_department_code": "93",
            "venue_is_virtual": False,
            "venue_fields_updated": "{}",
        },
        {
            "venue_managing_offerer_id": "4",
            "venue_id": "2",
            "venue_siret": "23456789000067",
            "venue_thumb_count": "0",
            "venue_name": "Test Venue",
            "venue_postal_code": "93",
            "venue_city": "Montreuil",
            "venue_department_code": "93",
            "venue_is_virtual": False,
            "venue_fields_updated": "{}",
        },
    ],
}
ENRICHED_OFFER_DATA_EXPECTED = [
    {
        "offer_id": "3",
        "offerer_id": "3",
        "offerer_name": "Test Offerer",
        "venue_id": "1",
        "venue_name": "Test Venue",
        "venue_department_code": "93",
        "offer_name": "Test",
        "offer_type": "EventType.CINEMA",
        "offer_creation_date": datetime(2019, 11, 20, 0, 0),
        "offer_is_duo": False,
        "venue_is_virtual": False,
        "physical_goods": False,
        "outing": True,
        "booking_cnt": 2.0,
        "booking_cancelled_cnt": 0.0,
        "booking_confirm_cnt": 0.0,
        "favourite_cnt": 2.0,
        "stock": 10.0,
        "offer_humanized_id": "AM",
        "passculture_pro_url": "https://pro.passculture.beta.gouv.fr/offres/AM",
        "webapp_url": "https://app.passculture.beta.gouv.fr/offre/details/AM",
        "first_booking_cnt": 1,
    },
    {
        "offer_id": "4",
        "offerer_id": "4",
        "offerer_name": "Test Offerer",
        "venue_id": "2",
        "venue_name": "Test Venue",
        "venue_department_code": "93",
        "offer_name": "RIP Dylan Rieder",
        "offer_type": "ThingType.LIVRE_EDITION",
        "offer_creation_date": datetime(2019, 11, 20, 0, 0),
        "offer_is_duo": False,
        "venue_is_virtual": False,
        "physical_goods": True,
        "outing": False,
        "booking_cnt": 0.0,
        "booking_cancelled_cnt": 0.0,
        "booking_confirm_cnt": 0.0,
        "favourite_cnt": 1.0,
        "stock": 12.0,
        "offer_humanized_id": "AQ",
        "passculture_pro_url": "https://pro.passculture.beta.gouv.fr/offres/AQ",
        "webapp_url": "https://app.passculture.beta.gouv.fr/offre/details/AQ",
        "first_booking_cnt": None,
    },
]

# enriched_stock_data
ENRICHED_STOCK_DATA_INPUT = {
    "booking": [
        {
            "user_id": "1",
            "stock_id": "1",
            "booking_id": "4",
            "booking_quantity": "2",
            "booking_creation_date": "2019-11-20",
            "booking_token": "ABC123",
            "booking_amount": "0",
            "booking_is_cancelled": False,
            "booking_is_used": False,
            "booking_used_date": "2019-11-22",
        }
    ],
    "offer": [
        {
            "venue_id": "1",
            "product_id": "1",
            "offer_id": "3",
            "offer_type": "EventType.CINEMA",
            "offer_name": "Test",
            "offer_is_active": True,
            "offer_media_urls": '["https://url.test", "https://someurl.test"]',
            "offer_url": None,
            "offer_is_national": False,
            "offer_creation_date": "2019-11-20",
            "offer_is_duo": False,
            "offer_fields_updated": "{}",
        },
        {
            "venue_id": "1",
            "product_id": "2",
            "offer_id": "2",
            "offer_type": "ThingType.LIVRE_EDITION",
            "offer_name": "Test bis",
            "offer_is_active": True,
            "offer_media_urls": '["https://url.test", "https://someurl.test"]',
            "offer_url": None,
            "offer_is_national": False,
            "offer_creation_date": "2019-11-20",
            "offer_is_duo": False,
            "offer_fields_updated": "{}",
        },
    ],
    "offerer": [
        {
            "offer_id": "3",
            "offer_thumb_count": "0",
            "offer_is_active": True,
            "offer_postal_code": "93100",
            "offer_city": "Montreuil",
            "offer_creation_date": "2019-11-20",
            "offer_name": "Test Offerer",
            "offer_siren": "123456789",
            "offer_fields_updated": "{}",
        }
    ],
    "payment": [
        {
            "bookingId": "4",
            "id": "1",
            "amount": "10",
            "reimbursementRule": "test",
            "reimbursementRate": "1",
            "recipientName": "Toto",
            "recipientSiren": "123456789",
            "author": "test",
        }
    ],
    "payment_status": [
        {"paymentId": "1", "id": "1", "date": "2019-01-01", "status": "PENDING"}
    ],
    "product": [
        {
            "id": "1",
            "type": "EventType.CINEMA",
            "thumbCount": "0",
            "name": "Livre",
            "mediaUrls": '["https://url.test", "https://someurl.test"]',
            "fieldsUpdated": "{}",
            "url": None,
            "isNational": False,
        },
        {
            "id": "1",
            "type": "ThingType.LIVRE_EDITION",
            "thumbCount": "0",
            "name": "Livre",
            "mediaUrls": '["https://url.test", "https://someurl.test"]',
            "fieldsUpdated": "{}",
            "url": None,
            "isNational": False,
        },
    ],
    "stock": [
        {
            "stock_id": "1",
            "offer_id": "3",
            "stock_creation_date": "2019-11-01",
            "stock_quantity": "10",
            "stock_booking_limit_date": "2019-11-23",
            "stock_beginning_date": "2019-11-24",
            "stock_is_soft_deleted": False,
            "stock_date_modified": "2019-11-20",
            "stock_price": "0",
            "stock_fieldsUpdated": "{}",
        },
        {
            "stock_id": "2",
            "offer_id": "2",
            "stock_creation_date": "2019-10-01",
            "stock_quantity": "12",
            "stock_booking_limit_date": None,
            "stock_beginning_date": None,
            "stock_is_soft_deleted": False,
            "stock_modified_date": "2019-11-20",
            "stock_price": "0",
            "stock_fields_updated": "{}",
        },
    ],
    "user": [
        {
            "user_id": "1",
            "user_email": "test@email.com",
            "user_can_book_free_offers": True,
            "user_is_admin": False,
            "user_postal_code": "93100",
            "user_department_code": "93",
            "user_public_name": "Test",
            "user_creation_date": "2018-11-20",
            "user_needs_to_fill_cultural_survey": True,
            "user_cultural_survey_filled_date": None,
        },
        {
            "user_id": "2",
            "user_email": "other@test.com",
            "user_can_book_free_offers": True,
            "user_is_admin": False,
            "user_postal_code": "93100",
            "user_department_code": "93",
            "user_public_name": "Test",
            "user_creation_date": "2018-11-20",
            "user_needs_to_fill_cultural_survey": True,
            "user_cultural_survey_filled_date": None,
        },
    ],
    "venue": [
        {
            "venue_managing_offerer_id": "3",
            "venue_id": "1",
            "venue_siret": None,
            "venue_thumb_count": "0",
            "venue_name": "Test Venue",
            "venue_postal_code": None,
            "venue_city": None,
            "venue_department_code": None,
            "venue_is_virtual": True,
            "venue_fields_updated": "{}",
        }
    ],
}

ENRICHED_STOCK_DATA_EXPECTED = [
    {
        "stock_id": "1",
        "offer_id": "3",
        "offer_name": "Test",
        "offerer_id": "3",
        "offer_type": "EventType.CINEMA",
        "venue_department_code": None,
        "stock_creation_date": datetime(2019, 11, 1),
        "stock_booking_limit_date": datetime(2019, 11, 23),
        "stock_beginning_date": datetime(2019, 11, 24),
        "available_stock_information": 8.0,
        "stock_quantity": 10.0,
        "booking_quantity": 2.0,
        "booking_cancelled": 0.0,
        "booking_paid": 2.0,
    },
    {
        "stock_id": "2",
        "offer_id": "2",
        "offer_name": "Test bis",
        "offerer_id": "3",
        "offer_type": "ThingType.LIVRE_EDITION",
        "venue_department_code": None,
        "stock_creation_date": datetime(2019, 10, 1),
        "stock_booking_limit_date": None,
        "stock_beginning_date": None,
        "available_stock_information": 12.0,
        "stock_quantity": 12.0,
        "booking_quantity": 0.0,
        "booking_cancelled": 0.0,
        "booking_paid": 0.0,
    },
]

# enriched_user_data => NO DATA (only structure can be tested)
ENRICHED_USER_DATA_INPUT = {
    "booking": [],
    "offer": [],
    "stock": [],
    "user": [],
}

ENRICHED_USER_DATA_EXPECTED = [
    "user_id",
    "experimentation_session",
    "user_department_code",
    "user_postal_code",
    "user_activity",
    "activation_date",
    "first_connection_date",
    "first_booking_date",
    "second_booking_date",
    "booking_on_third_product_date",
    "booking_cnt",
    "no_cancelled_booking",
    "user_seniority",
    "actual_amount_spent",
    "theoretical_amount_spent",
    "amount_spent_in_digital_goods",
    "amount_spent_in_physical_goods",
    "amount_spent_in_outings",
    "user_humanized_id",
    "last_booking_date",
]

# enriched_venue_data => NO DATA (only structure can be tested)
ENRICHED_VENUE_DATA_INPUT = {
    "booking": [],
    "favorite": [],
    "offer": [],
    "offerer": [],
    "payment": [],
    "payment_status": [],
    "stock": [],
    "venue": [],
    "venue_label": [],
    "venue_type": [],
}

ENRICHED_VENUE_DATA_EXPECTED = [
    "venue_id",
    "venue_name",
    "venue_booking_email",
    "venue_address",
    "venue_latitude",
    "venue_longitude",
    "venue_department_code",
    "venue_postal_code",
    "venue_city",
    "venue_siret",
    "venue_is_virtual",
    "venue_managing_offerer_id",
    "offerer_name",
    "venue_type_label",
    "venue_label",
    "total_bookings",
    "non_cancelled_bookings",
    "used_bookings",
    "first_offer_creation_date",
    "last_offer_creation_date",
    "offers_created",
    "theoretic_revenue",
    "real_revenue",
    "venue_humanized_id",
]

# enriched_offerer_data => NO DATA (only structure can be tested)
ENRICHED_OFFERER_DATA_INPUT = {
    "booking": [],
    "offer": [],
    "offerer": [],
    "stock": [],
    "venue": [],
    "venue_label": [],
    "venue_type": [],
}

ENRICHED_OFFERER_DATA_EXPECTED = [
    "offerer_id",
    "offerer_name",
    "offerer_creation_date",
    "first_stock_creation_date",
    "first_booking_date",
    "offer_cnt",
    "no_cancelled_booking_cnt",
    "offerer_department_code",
    "venue_cnt",
    "venue_with_offer",
    "offerer_humanized_id",
    "current_year_revenue",
]

# enriched_booking_data => NO DATA (only structure can be tested)
ENRICHED_BOOKING_DATA_INPUT = {
    "booking": [],
    "payment": [],
    "payment_status": [],
    "stock": [],
    "offer": [],
    "venue": [],
    "offerer": [],
    "user": [],
    "venue_type": [],
    "venue_label": [],
}

ENRICHED_BOOKING_DATA_EXPECTED = [
    "booking_id",
    "booking_creation_date",
    "booking_quantity",
    "booking_amount",
    "booking_is_cancelled",
    "booking_is_used",
    "booking_cancellation_date",
    "stock_beginning_date",
    "offer_type",
    "offer_name",
    "venue_name",
    "venue_label",
    "venue_type_label",
    "venue_department_code",
    "offerer_name",
    "user_department_code",
    "user_creation_date",
    "booking_intermediary_amount",
    "reimbursed",
    "physical_goods",
    "digital_goods",
    "event",
    "booking_rank",
    "same_category_booking_rank",
]
