FROM apache/airflow:2.9.1-python3.10
ARG AIRFLOW_USER_HOME=/opt/airflow

# Copy uv binary from the uv image
COPY --from=ghcr.io/astral-sh/uv:0.3.4 /uv /bin/uv
# Add binary to PATH
ENV PATH="/root/.cargo/bin/:$PATH"

# Install python dependencies
USER airflow
WORKDIR ${AIRFLOW_USER_HOME}
COPY k8-worker-requirements.txt /opt/requirements.txt
RUN uv pip install --no-cache-dir -r /opt/requirements.txt

ENTRYPOINT ["/usr/bin/dumb-init", "--", "/entrypoint"]
CMD []
