version: 1

sources:
  - name: clean # this is the source_name
    schema: clean_{{ env_var('ENV_SHORT_NAME') }} # this is the schema_name
    tables:
      - name: adage_involved_student # this is the table_name
      - name: applicative_database_bank_information
      - name: applicative_database_educational_year
      - name: applicative_database_offerer
      - name: applicative_database_venue
      - name: dms_jeunes_cleaned
      - name: dms_pro_cleaned
      - name: firebase_app_experiments
      - name: firebase_events
      - name: gsheet_eac_webinar
  - name: analytics # this is the source_name
    schema: analytics_{{ env_var('ENV_SHORT_NAME') }} # this is the schema_name
    tables:
      - name: adage

