version: 1

sources:
  - name: raw
    schema: raw_{{ var('ENV_SHORT_NAME') }}
    database: "{{ 'passculture-data-prod' if var('ENV_SHORT_NAME') == 'prod' else 'passculture-data-ehp' }}"
    tables:
      - name: adage
      - name: applicative_database_accessibility_provider
      - name: applicative_database_action_history
      - name: applicative_database_address
      - name: applicative_database_allocine_pivot
      - name: applicative_database_allocine_venue_provider
      - name: applicative_database_bank_account
      - name: applicative_database_beneficiary_fraud_check
      - name: applicative_database_beneficiary_fraud_review
      - name: applicative_database_beneficiary_fraud_status
      - name: applicative_database_beneficiary_import
      - name: applicative_database_beneficiary_import_status
      - name: applicative_database_booking
        data_tests:
          - elementary.volume_anomalies:
              tags: [elementary]
              timestamp_column: booking_creation_date
              anomaly_direction: both
              detection_period:
                period: day
                count: 1
              training_period:
                period: month
                count: 1
              time_bucket:
                period: day
                count: 1
              anomaly_sensitivity: 3
      - name: applicative_database_booking_finance_incident
      - name: applicative_database_boost_cinema_details
      - name: applicative_database_cashflow
      - name: applicative_database_cashflow_batch
      - name: applicative_database_cashflow_log
      - name: applicative_database_cashflow_pricing
      - name: applicative_database_cds_cinema_details
      - name: applicative_database_cgr_cinema_details
      - name: applicative_database_cinema_provider_pivot
      - name: applicative_database_collective_booking
      - name: applicative_database_collective_offer
      - name: applicative_database_collective_offer_domain
      - name: applicative_database_collective_offer_request
      - name: applicative_database_collective_offer_template
      - name: applicative_database_collective_offer_template_domain
      - name: applicative_database_collective_stock
      - name: applicative_database_criterion
      - name: applicative_database_criterion_category
      - name: applicative_database_criterion_category_mapping
      - name: applicative_database_custom_reimbursement_rule
      - name: applicative_database_deposit
      - name: applicative_database_discord_user
      - name: applicative_database_educational_deposit
      - name: applicative_database_educational_domain
      - name: applicative_database_educational_domain_venue
      - name: applicative_database_educational_institution
      - name: applicative_database_educational_institution_program
      - name: applicative_database_educational_institution_program_association
      - name: applicative_database_educational_redactor
      - name: applicative_database_educational_year
      - name: applicative_database_ems_cinema_details
      - name: applicative_database_favorite
      - name: applicative_database_feature
      - name: applicative_database_finance_event
      - name: applicative_database_finance_incident
      - name: applicative_database_google_places_info
      - name: applicative_database_headline_offer
      - name: applicative_database_internal_user
      - name: applicative_database_invoice
      - name: applicative_database_invoice_cashflow
      - name: applicative_database_invoice_line
      - name: applicative_database_local_provider_event
      - name: applicative_database_mediation
      - name: applicative_database_national_program
      - name: applicative_database_login_device_history
      - name: applicative_database_payment_message
      - name: applicative_database_payment
      - name: applicative_database_offerer_address
      - name: applicative_database_offerer_tag_mapping
      - name: applicative_database_offerer_tag_category_mapping
      - name: applicative_database_offerer_tag_category
      - name: applicative_database_offerer_tag
      - name: applicative_database_offer_legacy
      - name: applicative_database_offer_meta_data
      - name: applicative_database_offer_validation_sub_rule
      - name: applicative_database_offer_validation_rule
      - name: applicative_database_offer_report
      - name: applicative_database_offer_criterion
      - name: applicative_database_opening_hours
      - name: applicative_database_payment_status
      - name: applicative_database_price_category
      - name: applicative_database_price_category_label
      - name: applicative_database_pricing
      - name: applicative_database_pricing_line
      - name: applicative_database_pricing_log
      - name: applicative_database_product
      - name: applicative_database_product_mediation
      - name: applicative_database_product_whitelist
      - name: applicative_database_provider
      - name: applicative_database_recredit
      - name: applicative_database_stock
      - name: applicative_database_titelive_gtl
      - name: applicative_database_transaction
      - name: applicative_database_trusted_device
      - name: applicative_database_user
      - name: applicative_database_user_offerer
      - name: applicative_database_user_pro_new_nav_state
      - name: applicative_database_validation_rule_collective_offer_link
      - name: applicative_database_validation_rule_collective_offer_template_link
      - name: applicative_database_validation_rule_offer_link
      - name: applicative_database_venue
      - name: applicative_database_venue_bank_account_link
      - name: applicative_database_venue_contact
      - name: applicative_database_venue_criterion
      - name: applicative_database_venue_educational_status
      - name: applicative_database_venue_label
      - name: applicative_database_venue_pricing_point_link
      - name: applicative_database_venue_provider
      - name: applicative_database_venue_provider_external_urls
      - name: applicative_database_venue_registration
      - name: appsflyer_cost_channel
      - name: brevo_transactional
      - name: contentful_entry
      - name: contentful_relationship
      - name: contentful_tag
      - name: firebase_android_performance
      - name: firebase_events
      - name: firebase_ios_performance
      - name: firebase_pro_events
      - name: gsheet_eac_webinar
      - name: gsheet_educational_institution_student_headcount
      - name: gsheet_instagram_campaign_tag
      - name: gsheet_ml_recommendation_sensitive_item
      - name: gsheet_tiktok_campaign_tag
      - name: instagram_post_detail
      - name: metabase_collection
      - name: metabase_core_user
      - name: metabase_query_execution
      - name: metabase_report_card
      - name: metabase_report_dashboard
      - name: metabase_revision
      - name: qualtrics_answers
      - name: qualtrics_opt_out_users
      - name: qualtrics_exported_beneficiary_account
      - name: qualtrics_exported_venue_account
      - name: qpi_answers_historical
      - name: qpi_answers_v4
      - name: past_offer_context
      - name: raw_dms_jeunes
      - name: raw_dms_pro
      - name: sendinblue_transactional
      - name: sensitive_item_recommendation
      - name: stdout
      - name: subcategories
      - name: tiktok_video_detail
      - name: offer_types
      - name: user_address
      - name: zendesk_macro_usage
      - name: zendesk_ticket
      - name: zendesk_survey_response
  - name: clean
    schema: clean_{{ var('ENV_SHORT_NAME') }}
    database: "{{ 'passculture-data-prod' if var('ENV_SHORT_NAME') == 'prod' else 'passculture-data-ehp' }}"
    tables:
      - name: applicative_database_booking_history
      - name: applicative_database_stock_history
      - name: applicative_database_collective_booking_history
      - name: applicative_database_collective_stock_history
      - name: applicative_database_collective_offer_history
      - name: applicative_database_collective_offer_template_history
      - name: adage_involved_student
      - name: dms_jeunes_cleaned
      - name: dms_pro_cleaned
      - name: siren_data

  - name: analytics
    schema: analytics_{{ var('ENV_SHORT_NAME') }}
    database: "{{ 'passculture-data-prod' if var('ENV_SHORT_NAME') == 'prod' else 'passculture-data-ehp' }}"
    tables:
      - name: adage

  - name: seed
    schema: seed_{{ var('ENV_SHORT_NAME') }}
    database: "{{ 'passculture-data-prod' if var('ENV_SHORT_NAME') == 'prod' else 'passculture-data-ehp' }}"
    tables:
      - name: agg_partner_cultural_sector
      - name: epci
      - name: geo_iris
      - name: institution_metadata_aggregated_type
      - name: institutional_scholar_level
      - name: iris_france
      - name: iris_nesting
      - name: macro_rayons
      - name: population_age_and_department_france_details
      - name: priority_local_authorities
      - name: 2020_insee_iris_socio_demographics
      - name: 2024_insee_qpv
      - name: 2024_insee_qpv_population
      - name: 2025_insee_code
      - name: qpi_mapping
      - name: rural_city_type_data
      - name: region_department
      - name: siren_main_business_labels
      - name: siren_legal_category_labels
      - name: zrr

  - name: ml_preproc
    schema: ml_preproc_{{ var('ENV_SHORT_NAME') }}
    database: "{{ 'passculture-data-prod' if var('ENV_SHORT_NAME') == 'prod' else 'passculture-data-ehp' }}"
    tables:
      - name: default_item_cluster
      - name: item_embedding_extraction
      - name: item_embedding_reduced_64
      - name: item_embedding_reduced_32
      - name: item_embedding_reduced_16
      - name: item_embedding_reduced_5
      - name: artist
      - name: artist_alias
      - name: product_artist_link
      - name: delta_artist
      - name: delta_artist_alias
      - name: delta_product_artist_link
      - name: unconstrained_item_cluster
      - name: two_tower_user_embedding_history
        description: Partitionned table containing the history of the two tower user emebddings
      - name: two_tower_item_embedding_history
        description: Partitionned table containing the history of the two tower item emebddings
  - name: ml_linkage
    schema: ml_linkage_{{ var('ENV_SHORT_NAME') }}
    database: "{{ 'passculture-data-prod' if var('ENV_SHORT_NAME') == 'prod' else 'passculture-data-ehp' }}"
    tables:
      - name: item_offer_mapping
  - name: appsflyer_import
    schema: appsflyer_import_{{ var('ENV_SHORT_NAME') }}
    database: "{{ 'passculture-data-prod' if var('ENV_SHORT_NAME') == 'prod' else 'passculture-data-ehp' }}"
    tables:
      - name: cohort_unified_timezone_versioned
      - name: installs
