version: 1

exposures:
  - name: enriched_venue_data
    label: "venue"
    type: dashboard
    maturity: medium
    tags: ["jeunes","pro"]
    url: metabase.com
    description: >
      blabla
        
    depends_on:
      - ref('applicative_database_venue')
      - source('raw', 'applicative_database_venue')
      
    owner:
      name: data_analyst1
      email: data_analyst1@passculture.app

