table_name: product_whitelist
source_database: postgres
source_dataset: public
target_database: bigquery
columns:
- name: id
  input_data_type: varchar(255)
  output_data_type: STRING
  is_nullable: true
- name: title
  input_data_type: varchar(255)
  output_data_type: STRING
  is_nullable: true
- name: ean
  input_data_type: varchar(255)
  output_data_type: STRING
  is_nullable: true
- name: product_date_created
  input_data_type: UNKNOWN
  output_data_type: STRING
  is_nullable: true
- name: comment
  input_data_type: varchar(255)
  output_data_type: STRING
  is_nullable: true
- name: author_id
  input_data_type: varchar(255)
  output_data_type: STRING
  is_nullable: true
