name: "Base Workflow"

on:
  pull_request:

jobs:
   linter:
    uses: ./.github/workflows/reusable_linter.yml
    secrets:
      GCP_EHP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_EHP_WORKLOAD_IDENTITY_PROVIDER }}
      GCP_EHP_SERVICE_ACCOUNT: ${{ secrets.GCP_EHP_SERVICE_ACCOUNT }}
   find-dbt-changes:
    outputs:
      changes: ${{ steps.dbt-changes.outputs.changes }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "is dbt project modified?"
        id: dbt-changes
        env:
          TARGET_BRANCH: ${{ github.base_ref }}
        run: |
          git fetch origin $TARGET_BRANCH
          changed_files=$(git diff origin/$TARGET_BRANCH HEAD --name-only | grep 'orchestration/dags/data_gcp_dbt/' || true)
          if [ -z "$changed_files" ]; then
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "changes=true" >> $GITHUB_OUTPUT
          fi
   compile-dbt-on-prod:
    needs: find-dbt-changes
    if: github.base_ref == 'production' && needs.find-dbt-changes.outputs.changes == 'true'
    with:
      TARGET_COMPOSER_BUCKET: "europe-west1-data-composer--d5adf2e8-bucket"
      ENV_SHORT_NAME: "prod"
    uses: ./.github/workflows/reusable_dbt_compile.yml
    secrets:
      GCP_EHP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_EHP_WORKLOAD_IDENTITY_PROVIDER }}
      GCP_EHP_SERVICE_ACCOUNT: ${{ secrets.GCP_EHP_SERVICE_ACCOUNT }}
   compile-dbt-on-stg:
    needs: find-dbt-changes
    if: github.base_ref == 'master' && needs.find-dbt-changes.outputs.changes == 'true'
    with:
      TARGET_COMPOSER_BUCKET: "europe-west1-data-composer--00137508-bucket"
      ENV_SHORT_NAME: "stg"
    uses: ./.github/workflows/reusable_dbt_compile.yml
    secrets:
      GCP_EHP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_EHP_WORKLOAD_IDENTITY_PROVIDER }}
      GCP_EHP_SERVICE_ACCOUNT: ${{ secrets.GCP_EHP_SERVICE_ACCOUNT }}
   find-test-jobs:
     outputs:
       jobs: ${{ steps.compute.outputs.jobs }}
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Get etl_jobs changed files"
        id: "changed-etl-files"
        uses: tj-actions/changed-files@v41
        with:
          files: "jobs/etl_jobs/**"
          json: true
          dir_names: true
          dir_names_max_depth: 4
      - name: "Get ml_jobs changed files"
        id: "changed-ml-files"
        uses: tj-actions/changed-files@v41
        with:
          files: "jobs/ml_jobs/**"
          json: true
          dir_names: true
          dir_names_max_depth: 5
      - name: "Trouver les Jobs testables"
        id: "find-testable-jobs"
        run: |
          find jobs -type d  -name "tests" -exec dirname {} \; > /tmp/list.txt
          folders=()
          for folder in $(cat /tmp/list.txt); do
            folders+=(\\\"${folder}\\\")
          done
          json_array="[$(IFS=,; echo "${folders[*]}")]"
          echo "testable_jobs=$json_array" | tee -a $GITHUB_OUTPUT
      - name: "Show found files"
        id: "compute" # Intersection de testable_jobs et de (changed-etl-files et changed-ml-files)
        run: |
          echo "${{ steps.changed-etl-files.outputs.all_changed_files }}" > /tmp/output.json
          echo "${{ steps.changed-ml-files.outputs.all_changed_files }}" >> /tmp/output.json
          echo "${{ steps.find-testable-jobs.outputs.testable_jobs }}" >> /tmp/output.json
          cat /tmp/output.json
          jobs_to_test=$(jq --compact-output --slurp '(.[0] + .[1]) - ((.[0] + .[1]) - .[2])' /tmp/output.json)
          echo "jobs=${jobs_to_test}" | tee -a $GITHUB_OUTPUT
   assert-matrix-not-empty:
    needs: find-test-jobs
    if: ${{ needs.find-test-jobs.outputs.jobs != '' && toJson(fromJson(needs.find-test-jobs.outputs.jobs)) != '[]' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Matrix Not Empty"
   test-jobs:
    uses: ./.github/workflows/reusable_job_test.yml
    secrets:
      GCP_EHP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_EHP_WORKLOAD_IDENTITY_PROVIDER }}
      GCP_EHP_SERVICE_ACCOUNT: ${{ secrets.GCP_EHP_SERVICE_ACCOUNT }}
    needs: [assert-matrix-not-empty, find-test-jobs]
    strategy:
      fail-fast: false
      matrix:
        job: ${{ fromJSON(needs.find-test-jobs.outputs.jobs) }}
    with:
      JOB_PATH: ${{ matrix.job }}
   find-changed-orchestration:
     runs-on: ubuntu-latest
     outputs:
       run_tests: ${{ steps.changed-orchestration-files.outputs.any_modified }}
     steps:
      - name: Get changed files in orchestration folder
        id: changed-orchestration-files
        uses: tj-actions/changed-files@v41
        with:
          files: "orchestration/**"
   test-orchestration:
    needs: find-changed-orchestration
    if: needs.find-changed-orchestration.outputs.run_tests == 'true'
    uses: ./.github/workflows/reusable_test_orchestration.yml
    secrets:
      GCP_EHP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_EHP_WORKLOAD_IDENTITY_PROVIDER }}
      GCP_EHP_SERVICE_ACCOUNT: ${{ secrets.GCP_EHP_SERVICE_ACCOUNT }}