name: "[on_dispatch] build airflow image"

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  k8s-deploy-on-dev:
    needs: [find-build-job]
    uses: ./.github/workflows/reusable_build_image.yml
    with:
      TARGET_ENV: "dev"
      DATA_GCP_PROJECT: "passculture-data-ehp"
    secrets:
      GCP_EHP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_EHP_WORKLOAD_IDENTITY_PROVIDER }}
      GCP_EHP_SERVICE_ACCOUNT: ${{ secrets.GCP_EHP_SERVICE_ACCOUNT }}
