name: "Deploy Composer"

on:
 push:
   #   branches:
   #   - master
   #   - production

jobs:

  test-orchestration:
    uses: ./.github/workflows/reusable_test_orchestration.yml
    secrets:
      GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      ARTIFACT_REGISTRY_SERVICE_ACCOUNT: ${{ secrets.ARTIFACT_REGISTRY_SERVICE_ACCOUNT }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  composer-deploy-on-dev:
    #if: github.ref == 'refs/heads/production'
    uses: ./.github/workflows/reusable_deploy_composer.yml
    needs: 
      - test-orchestration
    with:
      TARGET_ENV:  "dev"
      COMPOSER_DAGS_BUCKET: "europe-west1-data-composer--a3134989-bucket"
      COMPOSER_ENVIRONMENT_NAME: "data-composer-dev"
      DATA_GCP_PROJECT: "passculture-data-ehp"
    secrets:
      GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      ARTIFACT_REGISTRY_SERVICE_ACCOUNT: ${{ secrets.ARTIFACT_REGISTRY_SERVICE_ACCOUNT }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  composer-deploy-on-stg:
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/reusable_deploy_composer.yml
    needs: 
      - test-orchestration
    with:
      TARGET_ENV:  "staging"
      COMPOSER_DAGS_BUCKET: "europe-west1-data-composer--00137508-bucket"
      COMPOSER_ENVIRONMENT_NAME: "data-composer-stg"
      DATA_GCP_PROJECT: "passculture-data-ehp"
    secrets:
      GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      ARTIFACT_REGISTRY_SERVICE_ACCOUNT: ${{ secrets.ARTIFACT_REGISTRY_SERVICE_ACCOUNT }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  composer-deploy-on-prod:
    if: github.ref == 'refs/heads/production'
    uses: ./.github/workflows/reusable_deploy_composer.yml
    needs: 
      - test-orchestration
      - composer-deploy-on-dev
    with:
      TARGET_ENV:  "prod"
      COMPOSER_DAGS_BUCKET: "europe-west1-data-composer--d5adf2e8-bucket"
      COMPOSER_ENVIRONMENT_NAME: "data-composer-prod"
      DATA_GCP_PROJECT: "passculture-data-prod"
    secrets:
      GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      ARTIFACT_REGISTRY_SERVICE_ACCOUNT: ${{ secrets.ARTIFACT_REGISTRY_SERVICE_ACCOUNT }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
