name: "Deploy Composer"

on:
 push:
   # branches:
      # - master
      # - production

jobs:

  test-jobs:
    uses: ./.github/workflows/reusable_test_jobs.yml

  # test-orchestration:
  #   uses: ./.github/workflows/reusable_test_orchestration.yml
  #   secrets:
  #     GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
  #     ARTIFACT_REGISTRY_SERVICE_ACCOUNT: ${{ secrets.ARTIFACT_REGISTRY_SERVICE_ACCOUNT }}

  composer-deploy-on-dev:  
    uses: ./.github/workflows/reusable_deploy_composer.yml
    needs: 
      - test-jobs
    with:
      TARGET_ENV:  "dev"
      COMPOSER_DAGS_BUCKET: "europe-west1-data-composer--a3134989-bucket"
      COMPOSER_ENVIRONMENT_NAME: "data-composer-dev"
      DATA_GCP_PROJECT: "passculture-data-ehp"
    secrets:
      GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      ARTIFACT_REGISTRY_SERVICE_ACCOUNT: ${{ secrets.ARTIFACT_REGISTRY_SERVICE_ACCOUNT }}


  composer-deploy-on-stg:
    if: github.ref == 'refs/heads/master'
    container: google/cloud-sdk:448.0.0
    runs-on: [self-hosted, linux, x64]
    defaults:
     run: 
       working-directory: "./orchestration/"
    steps:
      - uses: actions/checkout@v4
      - name: deploy on Staging
        run: echo "deploying on Saging"
      - name: Wait for composer
        run: echo "Wait for composer to be deployed (10s x 6 times)"

  composer-deploy-on-prod:
    if: github.ref == 'refs/heads/production'
    needs: composer-deploy-on-dev
    container: google/cloud-sdk:448.0.0
    runs-on: [self-hosted, linux, x64]
    defaults:
     run: 
       working-directory: "./orchestration/"
    steps:
      - name: deploy on Prod
        run: echo "deploying on Prod"
      - name: Wait for composer 
        run: echo "Wait for composer to be deployed (10s x 6 times)"