name: "4. [on_dispatch] build airflow image"

on:
  workflow_dispatch:
    inputs:
      CUSTOM_TAG:
        description: "Custom Docker image tag(s), 'dev' (default), 'v1' for stg and prod, 'v1,dev' to equalize envs"
        type: string
        required: false
        default: "dev"
      environment:
        description: "Environment to deploy to"
        type: choice
        required: true
        default: "dev"
        options:
          - dev
          - stg
          - prd

permissions:
  contents: write
  id-token: write

jobs:
  k8s-deploy-on-dev:
    uses: ./.github/workflows/reusable_build_image.yml
    with:
      GITHUB_ENV_NAME: ${{ inputs.environment }}
      TARGET_ENV: "dev"
      IS_MANUAL_DISPATCH: true
      CUSTOM_TAG: ${{ inputs.CUSTOM_TAG }}
      SOURCE_PATH: "orchestration/k8s-airflow"
      CONTEXT_PATH: .
      DOCKERFILE: "Dockerfile.k8s-worker"
      REGISTRY_BASE_NAME: "data-gcp/airflow"
    secrets:
      WORKLOAD_IDENTITY_PRD: ${{ secrets.WORKLOAD_IDENTITY_PRD }}
      PASSCULTURE_GITHUB_ACTION_APP_ID: ${{ secrets.PASSCULTURE_GITHUB_ACTION_APP_ID }}
      PASSCULTURE_GITHUB_ACTION_APP_PRIVATE_KEY: ${{ secrets.PASSCULTURE_GITHUB_ACTION_APP_PRIVATE_KEY }}
