name: "1. [on_pr] Prevent Merges on Master Allowed Hours"
on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - edited
  workflow_run:
    workflows:
      - on_schedule_rerun_check_hour
    types:
      - completed

jobs:
  check_time:
    runs-on: ubuntu-latest
    steps:
      - name: Get current time in Paris timezone with daylight saving
        id: get_time
        run: |
          # Get current Paris hour (00–23) by adjusting UTC time
          paris_hour=$(TZ='Europe/Paris' date +'%H')
          echo "PARIS_HOUR=$paris_hour" >> $GITHUB_ENV

      - name: Block merge if outside allowed hours (unless HF)
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          PARIS_HOUR: ${{ env.PARIS_HOUR }}
        run: |
          echo "PR title: $PR_TITLE"
          # If title starts with "(HF)", allow immediately
          if [[ "$PR_TITLE" == "(HF)"* ]]; then
            echo "Hotfix PR detected, bypassing merge window."
            exit 0
          fi

          echo "Paris hour: $PARIS_HOUR"
          # Block merges outside 12:00–18:00 Europe/Paris
          if [ $((10#$PARIS_HOUR)) -ge 18 ] || [ $((10#$PARIS_HOUR)) -lt 12 ]; then
            echo "Merges are not allowed between 18:00 and 12:00 TZ:Europe/Paris."
            exit 1
          else
            echo "Merge allowed."
          fi
