name: "1. [on_pr] Prevent Merges on Master Allowed Hours"
on:
  pull_request:
  # schedule:
  #   - cron: '0 10,11,16,17 * * 1-5' # Paris time with both daylight savings in UTC during weekdays
permissions:
  contents: write

jobs:
  call-github-api:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate with PAT
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}
        run: |
          gh auth login --with-token <<< "$GITHUB_TOKEN"

      - name: Get Branch Protection Rules
        run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            repos/${{ github.repository }}/branches/master/protection
