name: Run actionlint

on:
  push:
    branches:
      - main
    tags: "**"
  pull_request:

permissions:
  id-token: write
  contents: write

jobs:
  run_actionlint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: pass-culture/common-workflows/actions/actionlint-check@f4db7db202ff3cddc97fcbf08c3821ebc78b10fb
