name: "1. [on_pr] Prevent Merges on Master Allowed Hours"
on:
  pull_request:
  # schedule:
  #   - cron: '0 10,11,16,17 * * 1-5' # Paris time with both daylight savings in UTC during weekdays

jobs:
  call-github-api:
    runs-on: ubuntu-latest
    steps:
      - name: Make API Request with PAT
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              /repos/${{ github.repository }}/branches/master/protection
