name: "on_schedule_rerun_check_hour"
on:
  schedule:
    - cron: '0 10,11,16,17 * * 1-5' # Paris time with both daylight savings in UTC during weekdays
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize

jobs:
  re-run-worflow:
    runs-on: ubuntu-latest
    steps:
      - name: List workflow open branch with associated PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WORKFLOW_ID: 134227518
        run: |
          prs=$(gh pr list --json headRefName)
          # Loop over the PRs
          RUN_IDS=()
          echo "$prs" | jq -c '.[]' | while read -r pr; do
            branch=$(echo "$pr" | jq -r '.headRefName')
            echo "Branch $branch to re-run"
            RUN_IDS+=($(gh run list -b $branch -w $WORKFLOW_ID --json workflowDatabaseId | jq -r '.[]'))
          done
      - name : Re-run workflows
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo $RUN_IDS
          for RUN_ID in $RUN_IDS; do
            echo "Processing $RUN_ID"
            gh run rerun $RUN_ID
          done
