name: "on_schedule_rerun_check_hour"
on:
  schedule:
    - cron: '0 10,11,16,17 * * 1-5' # Paris time with both daylight savings in UTC during weekdays
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize

permissions: write-all

jobs:
  re-run-worflow:
    runs-on: ubuntu-latest
    steps:
      - name: List workflow open branch with associated PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WORKFLOW_ID: 134227518
          REPOSITORY: ${{ github.repository }}
        run: |
          prs=$(gh pr list --json headRefName -R $REPOSITORY)
          # Loop over the PRs
          RUN_IDS=()
          echo "$prs" | jq -c '.[]' | while read -r pr; do
            branch=$(echo "$pr" | jq -r '.headRefName')
            echo "Branch $branch to re-run"
            echo $(gh run list -b $branch -w $WORKFLOW_ID --json databaseId -R $REPOSITORY | jq -r '.[0].databaseId')
            RUN_ID=($(gh run list -b $branch -w $WORKFLOW_ID --json databaseId -R $REPOSITORY | jq -r '.[0].databaseId'))
            echo "gh run rerun $RUN_ID -R $REPOSITORY"
            gh run rerun 12475005462 -R pass-culture/data-gcp
            gh run rerun $RUN_ID -R $REPOSITORY
          done
      # - name : Re-run workflows
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     echo $RUN_IDS
      #     for RUN_ID in $RUN_IDS; do
      #       echo "Processing $RUN_ID"
      #       gh run rerun $RUN_ID -R $REPOSITORY
      #     done
