name: "[on_schedule] Rerun workflow"
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - ready_for_review
      - reopened
  schedule:
    - cron: '0 10,11,16,17 * * 1-5' # Paris time with both daylight savings in UTC during weekdays
  workflow_dispatch:


jobs:
  env:
    GH_TOKEN: ${{ secrets.github_token }}
  rerun_workflow:
    uses: ./.github/workflows/reusable_rerun_workflow.yml
