name: "Test Orchestration"

on:
  workflow_call:
    secrets:
       GCP_WORKLOAD_IDENTITY_PROVIDER:
        required: true
       ARTIFACT_REGISTRY_SERVICE_ACCOUNT:
        required: true
       SLACK_BOT_TOKEN:
        required: true

jobs:
  test-orchestration:
    permissions:
      id-token: write
      contents: write
    defaults:
     run: 
       working-directory: "./orchestration/"
    env:
      AIRFLOW_HOME: "./"
      DAG_FOLDER: "./dags"
      RECOMMENDATION_SQL_INSTANCE: cloudsql-recommendation-circleci
      RECOMMENDATION_SQL_BASE: cloudsql-recommendation-circleci
    name: "Test Orchestration"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
          cache-dependency-path: airflow/orchestration-requirements.txt
      - name: Install Python requirements
        run: |
            pip install -r airflow/orchestration-requirements.txt
      - id: auth
        name: "Authenticate with Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          create_credentials_file: true
          token_format: "access_token"
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.ARTIFACT_REGISTRY_SERVICE_ACCOUNT }}
      - name: Run tests
        env:
            GCP_PROJECT: passculture-data-ehp
            GOOGLE_CLOUD_PROJECT: passculture-data-ehp
            GCLOUD_PROJECT: passculture-data-ehp         
        run: |
          export PYTHONPATH=$PYTHONPATH:./dags
          airflow db init
          pytest tests
      - name: Post to a Slack channel
        id: slack
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: "C01GVAXM02W" # alertes-data
          payload: |
            {
                    "attachments": [
                        {
                            "mrkdwn_in": ["text"],
                            "color": "#A30002",
                            "author_name": "${{github.actor}}",
                            "author_link": "https://github.com/${{github.actor}}",
                            "author_icon": "https://github.com/${{github.actor}}.png",
                            "title": "Tests Orchestration",
                            "title_link": "https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}",
                            "text": "Les tests d'orchestration ont échoués"
                        }
                    ],
                    "unfurl_links": false,
                    "unfurl_media": false
            }
        env:
           SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
