name: "DBT build job"

on:
  workflow_call:
    inputs:
      NOTIF_CHANNEL_ID:
        type: string
        required: false # Si pas fourni, alors pas de notif
    secrets:
      GCP_EHP_WORKLOAD_IDENTITY_PROVIDER:
        required: true
      GCP_EHP_SERVICE_ACCOUNT:
        required: true
          
jobs:
  dbt-build:
    name: "dbt-build"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    defaults:
     run: 
       working-directory: "./orchestration/"
    env:
      AIRFLOW_HOME: "./"
      DAG_FOLDER: "./dags/"
      DBT_FOLDER: "./dags/data_gpc_dbt/"
      DBT_TARGET_BUCKET_PATH: "europe-west1-data-composer--00137508-bucket/data/target/"
    steps:
      - uses: actions/checkout@v4
      - name: "Connect to Secret Manager"
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.GCP_EHP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_EHP_SERVICE_ACCOUNT }}
      - name: "Get secrets for Slack"
        id: 'secrets'
        uses: 'google-github-actions/get-secretmanager-secrets@v2'
        with:
          secrets: |-
            SLACK_BOT_TOKEN:passculture-metier-ehp/passculture-ci-slack-bot-token
            ARTIFACT_REGISTRY_SERVICE_ACCOUNT:passculture-metier-ehp/passculture-main-artifact-registry-service-account
            ARTIFACT_REGISTRY_WORKLOAD_IDENTITY_PROVIDER:passculture-metier-ehp/infra-prod-gcp-workload-identity-provider
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
          cache-dependency-path: ./orchestration/airflow/orchestration-requirements.txt
      - name: "Install Python requirements"
        run: pip install -r airflow/orchestration-requirements.txt
      - name: "Authenticate with Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          create_credentials_file: true
          token_format: "access_token"
          workload_identity_provider: ${{ steps.secrets.outputs.ARTIFACT_REGISTRY_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ steps.secrets.outputs.ARTIFACT_REGISTRY_SERVICE_ACCOUNT }}
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
      - name: "install dbt dependencies"
        working-directory: "./orchestration/dags/data_gcp_dbt/"
        env:
          GCP_PROJECT: "passculture-data-ehp"
          GOOGLE_CLOUD_PROJECT: "passculture-data-ehp"
          GCLOUD_PROJECT: "passculture-data-ehp"
          DBT_TARGET_PATH: "target/"
          DBT_PROFILES_DIR: "."
        run: |
          export PYTHONPATH=$PYTHONPATH:./dags
          dbt deps 
      - name: "compile dbt project"
        working-directory: "./orchestration/dags/data_gcp_dbt/"
        env:
          GCP_PROJECT: "passculture-data-ehp"
          GOOGLE_CLOUD_PROJECT: "passculture-data-ehp"
          GCLOUD_PROJECT: "passculture-data-ehp"
          DBT_TARGET_PATH: "target/"
          DBT_PROFILES_DIR: "."
        run: |
          dbt compile

      - name: "list and build modified models"
        working-directory: "./orchestration/dags/data_gcp_dbt/"
        env:
          GCP_PROJECT: "passculture-data-ehp"
          GOOGLE_CLOUD_PROJECT: "passculture-data-ehp"
          GCLOUD_PROJECT: "passculture-data-ehp"
          DBT_TARGET_PATH: "target/"
          DBT_PROFILES_DIR: "."
          DBT_TARGET_BUCKET_PATH: "europe-west1-data-composer--00137508-bucket/data/target"
          DBT_DEFER_STATE: "./composer-run-artifacts/"
        run: |
          mkdir composer-run-artifacts
          gsutil cp gs://$DBT_TARGET_BUCKET_PATH/manifest.json ./composer-run-artifacts/manifest.json
          dbt ls --select "state:modified+" --state composer-run-artifacts
          dbt build --select "state:modified+" --defer --state composer-run-artifacts
      
      - name: "Post to a Slack channel"
        if: ${{ inputs.NOTIF_CHANNEL_ID != '' && failure() }}
        uses: slackapi/slack-github-action@v1.23.0
        env:
           SLACK_BOT_TOKEN: ${{ steps.secrets.outputs.SLACK_BOT_TOKEN }}
        with:
          channel-id: ${{ inputs.NOTIF_CHANNEL_ID }}
          payload: |
            {
              "attachments": [
                {
                  "mrkdwn_in": ["text"],
                  "color": "#A30002",
                  "author_name": "${{github.actor}}",
                  "author_link": "https://github.com/${{github.actor}}",
                  "author_icon": "https://github.com/${{github.actor}}.png",
                  "title": "Build dbt",
                  "title_link": "https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}",
                  "text": "Le build dbt a échoué"
                }
              ],
              "unfurl_links": false,
              "unfurl_media": false
            }
