name: "Linter job"

on:
  workflow_call:
    inputs:
      NOTIF_CHANNEL_ID:
        type: string
        required: false # Si pas fourni, alors pas de notif
    secrets:
      GCP_EHP_WORKLOAD_IDENTITY_PROVIDER:
        required: true
      GCP_EHP_SERVICE_ACCOUNT:
        required: true
      PASSCULTURE_GITHUB_ACTION_APP_ID:
        required: true
      PASSCULTURE_GITHUB_ACTION_APP_PRIVATE_KEY:
        required: true

jobs:
   linter:
    name: "linter job"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: "Connect to Secret Manager"
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.GCP_EHP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_EHP_SERVICE_ACCOUNT }}
      - name: "Get secrets for Slack"
        id: 'secrets'
        uses: 'google-github-actions/get-secretmanager-secrets@v2'
        with:
          secrets: |-
            PASSDIRECTOR_SLACK_BOT_TOKEN:passculture-metier-ehp/passculture-ci-slack-bot-token
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: "Install uv"
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      - name: "Authenticate through github app ghactionci"
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf
        id: github-token
        with:
          app-id: ${{ secrets.PASSCULTURE_GITHUB_ACTION_APP_ID }}
          private-key: ${{ secrets.PASSCULTURE_GITHUB_ACTION_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: passdirector
          permission-contents: read
      - name: "Install passdirector"
        run: |
          uv tool install --from "git+https://x-access-token:${{ steps.github-token.outputs.token }}@github.com/pass-culture/passdirector@main" passdirector
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
      - name : "Install linters (Ruff & sqlfmt)"
        run: uv sync
      - name: "Run linter (Ruff)"
        run: make ruff_check
      - name: "Run sql linter (sqlfmt)"
        run: make sqlfmt_check
      - name: "Post to a Slack channel"
        id: "slack"
        if: ${{ inputs.NOTIF_CHANNEL_ID != '' && failure() }}
        env:
          PASSDIRECTOR_SLACK_BOT_TOKEN: ${{ steps.secrets.outputs.PASSDIRECTOR_SLACK_BOT_TOKEN }}
          NOTIF_CHANNEL_ID: ${{ inputs.NOTIF_CHANNEL_ID }}
        run: |
          passdirector slack post \
            --channel "$NOTIF_CHANNEL_ID" \
            --message ":fire: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Linter job échoué> :no_entry:" \
            --github-actor "${{ github.actor }}"
