name: "Test job"

run-name: "Test job ${{ inputs.JOB_PATH }}"

on:
  workflow_call:
    inputs:
      JOB_PATH:
        type: string
        required: true
      NOTIF_CHANNEL_ID:
        type: string
        required: false # Si pas fourni, alors pas de notif
    secrets:
      GCP_EHP_WORKLOAD_IDENTITY_PROVIDER:
        required: true
      GCP_EHP_SERVICE_ACCOUNT:
        required: true

env:
  GCP_REGION: "europe-west1"

jobs:
  test-job:
    name: "Test job ${{ inputs.JOB_PATH }}"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    defaults:
     run: 
       working-directory: "./${{ inputs.JOB_PATH }}"
    steps:
      - uses: actions/checkout@v4
      - name: "Connect to Secret Manager"
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.GCP_EHP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_EHP_SERVICE_ACCOUNT }}
      - name: "Get secrets for Slack"
        id: 'secrets'
        uses: 'google-github-actions/get-secretmanager-secrets@v2'
        with:
          secrets: |-
            SLACK_BOT_TOKEN:passculture-metier-ehp/passculture-ci-slack-bot-token
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
          cache-dependency-path:  "./${{ inputs.JOB_PATH }}/requirements.txt"
      - name: "Install Python requirements"
        run:  pip install -r requirements.txt
      - name: "Run tests"
        run: pytest tests
        env:
          PYTHONPATH: "."
      - name: "Post to a Slack channel"
        if: ${{ inputs.NOTIF_CHANNEL_ID != '' && failure() }}
        uses: slackapi/slack-github-action@v1.23.0
        env:
          SLACK_BOT_TOKEN: ${{ steps.secrets.outputs.SLACK_BOT_TOKEN }}
        with:
          channel-id: ${{ inputs.NOTIF_CHANNEL_ID }}
          payload: |
            {
              "attachments": [
                {
                  "mrkdwn_in": ["text"],
                  "color": "#A30002",
                  "author_name": "${{github.actor}}",
                  "author_link": "https://github.com/${{github.actor}}",
                  "author_icon": "https://github.com/${{github.actor}}.png",
                  "title": "Test jobs échoués",
                  "title_link": "https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}",
                  "text": ":fire: Les tests sur le job ${{ inputs.JOB_PATH }} ont échoués :no_entry:"
                }
              ],
              "unfurl_links": false,
              "unfurl_media": false
            }
    
