name: "rerun_workflow"
on:
  workflow_call:

jobs:
  re-run-worflow:
    runs-on: ubuntu-latest
    steps:
      - name: List workflow open branch with associated PR
        run: |
          prs=$(gh pr list --json headRefName)
          # Loop over the PRs
          RUN_IDS=()
          echo "$prs" | jq -c '.[]' | while read -r pr; do
            branch=$(echo "$pr" | jq -r '.headRefName')
            echo "Branch $branch to re-run"
            RUN_IDS+=($(gh run list -b $branch -w 134227518 --json workflowDatabaseId | jq -r '.[]'))
          done
      - name : Re-run workflows
        run: |
          echo $RUN_IDS
          for RUN_ID in $RUN_IDS; do
            echo "Processing $RUN_ID"
            gh run rerun $RUN_ID
          done
