name: "Test Orchestration"

on:
 push:

jobs:
  test-orchestration:
    defaults:
     run: 
       working-directory: "./orchestration/"
    name: "Test Orchestration"
    runs-on: [self-hosted, linux, x64]
    container: python:3.7
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4.7.0
        with:
         python-version: "3.7"
      - name: Install Python requirements
        run: |
            pip install -r airflow/orchestration-requirements.txt
      - name: Run tests
        run: |
          airflow db init
          pytest tests