INSTALLS_REPORT = {
    "Install Time": "install_time",
    "Event Time": "event_time",
    "Event Name": "event_name",
    "Is Receipt Validated": "is_receipt_validated",
    "Partner": "partner",
    "Media Source": "media_source",
    "Channel": "channel",
    "Keywords": "keywords",
    "Campaign": "campaign",
    "Campaign ID": "campaign_id",
    "Region": "region",
    "Country Code": "country_code",
    "State": "state",
    "City": "city",
    "Postal Code": "postal_code",
    "DMA": "dma",
    "IP": "ip",
    "WIFI": "wifi",
    "Operator": "operator",
    "Carrier": "carrier",
    "Language": "language",
    "AppsFlyer ID": "appsflyer_id",
    "Advertising ID": "advertising_id",
    "OS Version": "os_version",
    "App Version": "app_version",
    "SDK Version": "sdk_version",
    "App ID": "app_id",
    "App Name": "app_name",
    "Bundle ID": "bundle_id",
    "Is Retargeting": "is_retargeting",
    "User Agent": "user_agent",
    "Device Category": "device_category",
    "Google Play Referrer": "google_play_referrer",
    "Google Play Click Time": "google_play_click_time",
    "Google Play Install Begin Time": "google_play_install_begin_time",
}

INSTALLS_REPORT_MAPPING = {
    "install_time": str,
    "event_time": str,
    "event_name": str,
    "is_receipt_validated": str,
    "partner": str,
    "media_source": str,
    "channel": str,
    "keywords": str,
    "campaign": str,
    "campaign_id": str,
    "region": str,
    "country_code": str,
    "state": str,
    "city": str,
    "postal_code": str,
    "dma": str,
    "ip": str,
    "wifi": bool,
    "operator": str,
    "carrier": str,
    "language": str,
    "appsflyer_id": str,
    "advertising_id": str,
    "os_version": str,
    "app_version": str,
    "sdk_version": str,
    "app_id": str,
    "app_name": str,
    "bundle_id": str,
    "is_retargeting": bool,
    "user_agent": str,
    "device_category": str,
    "google_play_referrer": str,
    "google_play_click_time": str,
    "google_play_install_begin_time": str,
}

DAILY_REPORT = {
    "Date": "date",
    "Agency/PMD (af_prt)": "agency",
    "Media Source (pid)": "media_source",
    "Campaign (c)": "campaign",
    "Impressions": "impressions",
    "Clicks": "clicks",
    "CTR": "ctr",
    "Installs": "installs",
    "Conversion Rate": "conversion_rate",
    "Sessions": "sessions",
    "Loyal Users": "loyal_users",
    "Total Cost": "total_cost",
    "Average eCPI": "average_ecpi",
}

DAILY_REPORT_MAPPING = {
    "date": str,
    "agency": str,
    "media_source": str,
    "campaign": str,
    "impressions": float,
    "clicks": float,
    "ctr": float,
    "installs": float,
    "conversion_rate": float,
    "sessions": float,
    "loyal_users": float,
    "total_cost": float,
    "average_ecpi": float,
}

APP_REPORT = {
    "Attributed Touch Type": "attributed_touch_type",
    "Attributed Touch Time": "attributed_touch_time",
    "Install Time": "install_time",
    "Event Time": "event_time",
    "Event Name": "event_name",
    "Event Value": "event_value",
    "Event Revenue": "event_revenue",
    "Event Revenue Currency": "event_revenue_currency",
    "Event Revenue Preferred": "event_revenue_preferred",
    "Event Source": "event_source",
    "Is Receipt Validated": "is_receipt_validated",
    "Partner": "partner",
    "Media Source": "media_source",
    "Channel": "channel",
    "Keywords": "keywords",
    "Campaign": "campaign",
    "Campaign ID": "campaign_id",
    "Adset": "adset",
    "Adset ID": "adset_id",
    "Ad": "ad",
    "Region": "region",
    "Country Code": "country_code",
    "State": "state",
    "City": "city",
    "Postal Code": "postal_code",
    "DMA": "dma",
    "IP": "ip",
    "WIFI": "wifi",
    "AppsFlyer ID": "appsflyer_id",
    "Advertising ID": "advertising_id",
    "IDFA": "idfa",
    "Android ID": "android_id",
    "Customer User ID": "customer_user_id",
    "IMEI": "imei",
    "IDFV": "idfv",
    "Platform": "platform",
    "Device Type": "device_type",
    "OS Version": "os_version",
    "App Version": "app_version",
    "SDK Version": "sdk_version",
    "App ID": "app_id",
    "App Name": "app_name",
    "Bundle ID": "bundle_id",
    "Is Retargeting": "is_retargeting",
    "Retargeting Conversion Type": "retargeting_conversion_type",
    "Attribution Lookback": "attribution_lookback",
    "Reengagement Window": "reengagement_window",
    "Is Primary Attribution": "is_primary_attribution",
    "User Agent": "user_agent",
}

APP_REPORT_MAPPING = {
    "attributed_touch_type": str,
    "attributed_touch_time": str,
    "install_time": str,
    "event_time": str,
    "event_name": str,
    "event_value": str,
    "event_revenue": str,
    "event_revenue_currency": str,
    "event_revenue_preferred": str,
    "event_source": str,
    "is_receipt_validated": str,
    "partner": str,
    "media_source": str,
    "channel": str,
    "keywords": str,
    "campaign": str,
    "campaign_id": str,
    "adset": str,
    "adset_id": str,
    "ad": str,
    "region": str,
    "country_code": str,
    "state": str,
    "city": str,
    "postal_code": str,
    "dma": str,
    "ip": str,
    "wifi": bool,
    "appsflyer_id": str,
    "advertising_id": str,
    "idfa": str,
    "android_id": str,
    "customer_user_id": str,
    "imei": str,
    "idfv": str,
    "platform": str,
    "device_type": str,
    "os_version": str,
    "app_version": str,
    "sdk_version": str,
    "app_id": str,
    "app_name": str,
    "bundle_id": str,
    "is_retargeting": str,
    "retargeting_conversion_type": str,
    "attribution_lookback": str,
    "reengagement_window": str,
    "is_primary_attribution": str,
    "user_agent": str,
}
